version: '3'

services:
  nakama:
    image: nakama
    ports:
      - "7350:7350"
  room:
    image: room
    ports:
      - "7650:7650"
  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - logpose:/var/lib/influxdb2
  redis:
    image: redis:7-alpine
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"

volumes:
  logpose:
