version: '3'

services:
  nakama:
    image: nakama
    ports:
      - "7350:7350"
  room:
    image: room
    ports:
      - "7650:7650"
  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - logpose:/var/lib/influxdb2

volumes:
  logpose:
